In [1]:
import numpy as np

In [2]:
inputs =  [[1, 2, 3, 2.5],
           [2, 5, -1, 2],
           [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

In [3]:
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer1_outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [4]:
weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
layer2_outputs

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [5]:
########################################################################

In [6]:
import numpy as np
np.random.seed(0)

X =  [[1, 2, 3, 2.5],
      [2, 5, -1, 2],
      [-1.5, 2.7, 3.3, -0.8]]


In [7]:
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

In [9]:
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.07600385  0.04015067]
 [-0.03707247 -0.0575363 ]
 [ 0.04924432  0.02825296]]


## Activation functions

we use sigmoid or rectified linear function instead of step because gradual change is good for optimizer

sigmoid function has problem - saturates and kills gradient

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)